### ISSUE TITLE
Probleme mit GPIO Belegung

### ISSUE THREAD

**Issue by axelb9999** [Tronje-the-Falconer/Pi-Ager#103]
Hallo,
erstmal großen Respekt für das tolle Projekt. Absolut geil. 
Ich habe den Schrank Hardware seitig nachgebaut. Als erste Inspiration bin ich nach der Anleitung von Opa Jochens Projekt gegangen. 
![IMG_1965](https://user-images.githubusercontent.com/76946003/147222974-8fd86d68-462c-4247-86b4-cfe38e58cfca.jpg)
![IMG_1964](https://user-images.githubusercontent.com/76946003/147222978-1c927680-3027-455e-854e-5ea70ee37034.jpg)

Da ich aber mit Programmierung nix am Hut habe, bin ich hierbei dann auf das Projekt PiAger gestoßen und habe mir für die Steuerung der Komponenten das Release 3.3.1 als komplettes Image auf meinen Pi 3B+ gezogen. Mit der Einrichtung hat auch soweit alles geklappt. 
Jetzt mein Problem:
Bei der vorgegeben Belegung der GPIO´s laut diesem Schema:

![image](https://user-images.githubusercontent.com/76946003/147222281-4deb795b-5d6b-409c-855b-cca445d54524.png)

ist mir aufgefallen, dass Kühlung und Heizung vertauscht sind.(auf dem Bild habe ich die Anschlüsse schon getauscht, sodass beim Kühlen auch der Kompressor und beim Heizen auch die Heizpads angehen) Auch der Befeuchter läuft durchgehend, obwohl auf der Weboberfläche etwas anderes angezeigt wird. Das gleiche mit Umluft und Abluft. 
Ist es auch normal, dass die Relais schon freischaltet, obwohl per Weboberfläche der PiAger noch nicht gestartet ist?

![IMG_1973](https://user-images.githubusercontent.com/76946003/147222515-ddaf3104-de35-4e99-b75b-07f8e4eff43b.jpg)
![IMG_1974](https://user-images.githubusercontent.com/76946003/147222518-d43f3e86-93e9-426a-a9b4-a8a6d1f7f28a.jpg)
![IMG_1975](https://user-images.githubusercontent.com/76946003/147222521-76523c3c-1d6b-4d0a-aaf2-61d45101ec62.jpg)

Bitte habt Rücksicht, wenn ich mich nicht in IT Sprache ausdrücken kann. ;-))
Ich füge noch Bilder meines Raspberrys und des Relaimoduls bei.

**Comment by GSV-Ha-Ma** [comment]
1. Hier im Forum kannst du besser deine Fragen stellen  


https://www.grillsportverein.de/forum/threads/verkaufsportal-pi-ager-reifeschrank-platine.288119/

https://www.grillsportverein.de/forum/threads/pi-ager-reifeschranksteuerung-mittels-raspberry-pi-release-3-3-1.342426/page-11#post-4958414

2. Prüf bitt deine Verdrahtung mal genauer, bei dir ist z.B. Eingang 1 von Relaisboard garnicht belegt…
Falls du es noch nicht gefunden hast, hier z.B. findest du auch den Schaltplan, 

https://github.com/Tronje-the-Falconer/Pi-Ager/tree/resources/platine/circuit

**Comment by GSV-Ha-Ma** [comment]
Bitte GPIO und Pin nicht verwechseln!!!!
Beide sind sauber sowohl im Schaltplan als auch auf der Relaisbeschriftung zu finden.

**Comment by axelb9999** [comment]
> 1. Hier im Forum kannst du besser deine Fragen stellen
> 
> https://www.grillsportverein.de/forum/threads/verkaufsportal-pi-ager-reifeschrank-platine.288119/
> 
> https://www.grillsportverein.de/forum/threads/pi-ager-reifeschranksteuerung-mittels-raspberry-pi-release-3-3-1.342426/page-11#post-4958414
> 
> 2. Prüf bitt deine Verdrahtung mal genauer, bei dir ist z.B. Eingang 1 von Relaisboard garnicht belegt…
>    Falls du es noch nicht gefunden hast, hier z.B. findest du auch den Schaltplan,
> 
> https://github.com/Tronje-the-Falconer/Pi-Ager/tree/resources/platine/circuit

zu1) ich poste es auch mal dort
zu2) ich habe auf dem Relaisboard folgendes belegt -> 1 = frei; 2 = Kompressor; 3 = Heizung; 4 = Vernebler; 5 = Austauschlüfter; 6 = Umlüfter; 7 = frei; 8 = frei

**Comment by GSV-Ha-Ma** [comment]
Die Belegung ist halt falsch... schau dir den Schaltplan mal an.

**Comment by axelb9999** [comment]
> Bitte GPIO und Pin nicht verwechseln!!!! Beide sind sauber sowohl im Schaltplan als auch auf der Relaisbeschriftung zu finden.

**Comment by axelb9999** [comment]
> 

so habe das Relaismodul und die PIN Belegung nun genau nach dem Schaltplan angeschlossen. Aktuell sieht es dann so aus:

Im Relais sind Heizung und Vernebler an.
![IMG_1976](https://user-images.githubusercontent.com/76946003/147247562-888366d3-3b88-45c2-bcf6-c9847d66df72.jpg)

In der Weboberfläche steht folgendes:

![IMG_1977](https://user-images.githubusercontent.com/76946003/147247607-a0e98ccd-c551-48f7-a054-ee2362fb8332.jpg)

**Comment by GSV-Ha-Ma** [comment]
Sei mit bitte nicht böse, die Gpio Belegung funktioniert bei allen anderen daher passt alles, der Fehler liegt nicht an der Software;-) 
Um genau diese „Probleme“ zu vermeiden hatten wir die Platine entwickelt damit User die nicht so viel Erfahrung haben es leichter haben.

Wenn du wirklich alles richtig verdrahtet hast, hast du vielleicht den GPiO vom Raspberrys „geschossen“ ...
Auf deinen Bildern kann man auch nicht wirklich was sehen und vervolgen.

Bitte wechsel jetzt ins Forum.
