### ISSUE TITLE
FRQ: implementieren einer Verzögerungszeit beim Wiedereinschalten des Kompressors

### ISSUE THREAD

**Issue by GSV-Ha-Ma** [Tronje-the-Falconer/Pi-Ager#106]
Da es in verschiedenen Fälle dazu kommen könnte, dass nach einem Ausschalten das Kompressor dieser sofort wieder eingeschaltet werden soll (z.B. Öffnen der Tür und der dadurch verursachten Temperaturerhöhung)macht es Sinn hier beim Wiedereinschlafen eine Verzögerung einzubauen um den Kompressor zu schützen.

**Comment by phylax2020** [comment]
Fixed in v3.3.3
