### ISSUE TITLE
BUG: custom statistics show more than one year and can't be set back to other smaller timeframe (i.e. 5 min.)

### ISSUE THREAD

**Issue by ggrilnberger** [Tronje-the-Falconer/Pi-Ager#108]
### Expected behavior

custom statistics set to any custom value

### actual behavior

custom statistics set doesn't set graphics, it shows 3 years (now --> 4 years)

### Steps to reproduce the problem.

set custom statistics to 12 month + (at least ) 1 minute
every time you do it again it will add another year (see pictures)

it can't be set back to (i.e.) 5 minutes

### Possible Solution

???

### Specifications like the version of the project, operating system, or hardware

Pi-ager 3.3.0
Raspberry 3B

<img width="960" alt="Bildschirmfoto 2022-02-15 um 15 29 24" src="https://user-images.githubusercontent.com/71764967/154082564-efdfb423-1684-4a94-b41e-d2ddc079d6bf.png">
<img width="934" alt="Bildschirmfoto 2022-02-15 um 15 30 20" src="https://user-images.githubusercontent.com/71764967/154082589-e0cc2951-3153-4a1b-9511-8f6bbd4ac160.png">
B

**Comment by phylax2020** [comment]
fixed in rev 3.3.3
