### ISSUE TITLE
Reifetabellen in sqlite zur Kontrolle lesbar/editierbar machen

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#15]

**Comment by Tronje-the-Falconer** [comment]
Lesbar ist es bereits mit Lösung durch Steinbacher

**Comment by GSV-Steinbacher** [comment]
Editierbar könnte ich mir über Formular vorstellen. Und zwar direkt in der Ansicht unter EINSTELLUNGEN:
Neu anlegen -> Speichern
Ändern -> Speichern
Löschen

**Comment by Tronje-the-Falconer** [comment]
löschen im nächsten Release möglich

**Comment by Tronje-the-Falconer** [comment]
In neuem release möglich
