### ISSUE TITLE
neue Einträge im Logfile oben anfügen.

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#19]

**Comment by GSV-Steinbacher** [comment]
Das war schon mal so. Das war nur elends umständlich mit der Vorgabe "Lesbare Formatierung" zu vereinbaren. Deshalb habe ich das seinerzeit rausgenommen...

**Comment by Tronje-the-Falconer** [comment]
zu aufwändig und ineffizient
