### ISSUE TITLE
Programmabbruch durch Stromausfall abfangen

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#23]
Programmende und nächste Periode Zeit in settings.json

nach Pi start, die Pythondateien automatisch ausführen und überprüfen ob das Programm unterbrochen wurde (settings.json?)
An korrekter Stelle weitermachen

**Comment by GSV-Steinbacher** [comment]
Auch ohne Programmabbruch den Reifeprozess 
- anhalten (Pause)
- an gleicher Stelle fortsetzen (Start)

**Comment by Tronje-the-Falconer** [comment]
in zukünfzigen Release enthalten
