### ISSUE TITLE
Auslagern der Hardwarewerte in neue JSON-Datei

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#25]
neue JSON datei mit Sensortyp, und Variablen für Steuerungsoption.
Im Frontend wählbar machen, ob mittels Relais, Wifi Steckdose oder Funksteckdose geschaltet wird.
Setzt vorraus, dass diese Steuerungsmöglichkeiten gegeben sind.

In der Settings.php Bereich einfügen der das dazugehörige Formular enthält. Einblenden mittels Button ermöglichen, um die settings-Seite nicht zu überfrachten. Diese Einstellung macht man nicht häufig, bzw. nur 1x

**Comment by GSV-Steinbacher** [comment]
Sehr gute Idee, oder vielleicht in eine Config-Datei, die im Rahmen einer kleinen Installationsroutine befüllt wird

**Comment by Tronje-the-Falconer** [comment]
in nächster Version enthalten
