### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#26]
in ferner Zukunft könnte man auch ein Touchdisplay, wie beim WLan-Thermo einsetzen, um direkt am Schrank änderungen zu machen oder Einstellungen zu sehen

**Comment by GSV-Steinbacher** [comment]
Das fände ich auch viel hübscher!

**Comment by phylax2020** [comment]
Nextion TFT touch display now supported in rev. 3.3.3
