### ISSUE TITLE
website erstellen

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#27]
Über GitHub können wir auch eine Website erstellen, wenn gewünscht:
[Git Hub Pages](https://pages.github.com/)

**Comment by GSV-Steinbacher** [comment]
Och, cool- das können wir machen!

**Comment by Tronje-the-Falconer** [comment]
Aufgrund des Wiki's und der vielfältigen Möglichkeiten auf Github stelle ich das mal zur Diskussion.
Meine Meinung: Das braucht es das nicht, da wir hier alles Erschlagen können. Nur für eine eigene URL lohnt der aufwand nicht.

**Comment by GSV-Ha-Ma** [comment]
Denke die Git Wiki ist vollkommen ausreichend , vorallem man kann auch sehr gut parallel daran arbeiten

**Comment by Tronje-the-Falconer** [comment]
Flatmike sieht es ebenfalls so. -> Mehrheit Also wird dies geschlossen und wohl nicht gemacht
