### ISSUE TITLE
ein und ausschaltwerte für Temp und Luftfeuchtigkeit aus Reifetabelle entfernen

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#28]
Um die Tabelle zu entschlacken sollten diese Werte ausgebaut werden. Diese Werte werden einmal für das System ermittelt und verändern sich nicht.
Die Werte müssen dafür in der reifetab.py aus der Settings.json ausgelesen werden.

**Comment by GSV-Ha-Ma** [comment]
? Sollen die Werte weil die nicht mehr überschrieben werden dann im Automatik Modus wieder eingeblendet werden so dass man in den x Tagen wenn das Programm läuft die Regelung noch nachträglich optimieren kann? Das macht wahrscheinlich Sinn....

**Comment by GSV-Steinbacher** [comment]
Genau, Ha-Ma, die Hysteresewerte (=Ein/Ausschaltwerte) sind schrankeigentümlich und bauartbedingte Werte, die sich bei unterschiedlicher Nutzung (viel Fleisch - wenig Fleisch) mal ändern können. Das kommt auf die Menge der Feuchtigkeit und der damit verbundenen Wärmekapazität an. Daher ist der Vorschlag sehr gut, die Werte aus der Reifetab zu entfernen und in einen bedienbaren Bereich zu verlegen, damit diese ggf. wärend der Reife noch angepasst werden können. Alle anderen Werte, die von der Reifetab gesteuert werden, sollten unsichtbar bleiben...

**Comment by Tronje-the-Falconer** [comment]
In neuer Version erledigt
