### ISSUE TITLE
Dauerhafte Temperatur und Feuchtigkeitsmessung

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#3]
Die Tempeartur unf Feuchtigkeitsmessung dauerhaft machen, ohne das ein Steuerungsprogramm eingeschaltet sein muss

**Comment by GSV-Steinbacher** [comment]
Ich habe die Anzeige jetzt so programmiert, dass die Werte nur angezeigt werden, wenn es aktuelle Werte sind == Kontrolle, ob mein Schrank/Sensor funktionieren

**Comment by Tronje-the-Falconer** [comment]
Ich meine damit, das dauerhaft die Tempeartur angezeigt wird, egal ob RSS-Steuerung läuft oder nicht.
Evtl. ist es auch sonnlos, da ja nur mit laufender Steuerung auch gekühlt wird...? Dann wäre autostart mit RSS.py sinnvoll

**Comment by GSV-Ha-Ma** [comment]
Sinn macht es wenn man eine Umschaltung hat zw. RSS und originalem Thermostat damit man den Kühlschrank doch noch weiter "beobachten " kann.

**Comment by Tronje-the-Falconer** [comment]
Ich glaube das macht man nicht. Durch den "nur Kühlen" Modus ist ja auch jetzt die ursprüngliche Funktion des Kühlschrankes wieder implementiert.
Daher sollte man direkt nach dem Systemstart die RSS.py starten (Dienst). Dann hat man sofort Werte und der Kühlschrank läuft.
Setzt voraus: [Auslagern der Hardwarewerte in neue JSON-Datei](https://github.com/Tronje-the-Falconer/Reifeschrank/issues/25) und befüllen über das noob Image. (Sensor, Steuerungsmodus [Relais,Wifi,Funk])

Des weitern muss dann die Settings evtl. angepasst werden, dass der button StartRS nach unten zu den Systembuttons wandert und RestartRS lautet?

**Comment by Tronje-the-Falconer** [comment]
das neue Release beinhaltet einen Stromausfall. D.H. alte werte werden nachdem der Strom wieder da ist genutzt.
Ausliefeungszustand eines Release sollte zustand aus sein. Dann kann jeder so konfigurieren wie er möchte.
