### ISSUE TITLE
Reifecam 

### ISSUE THREAD

**Issue by GSV-Ha-Ma** [Tronje-the-Falconer/Pi-Ager#30]
Wir sollten eine "Reifecam" integrieren, so dass man dem Reifeprozess beobachten kann und was viel interessanter ist:  =>  diesen Prozess sich dann später in Zeitraffer anzuschauen...
Man könnte in regelmäßigen Abschnitten immer ein Bild abspeichern und diese Bilder dann nach der Reifezeit zu einem Zeitraffervideo zusammenfasen.
Da viele Kühlschränke ja eine Beleuchtung haben kann das sogar gut funktionieren...

**Comment by Tronje-the-Falconer** [comment]
In neuer Version enthalten

**Comment by sickboy2711** [comment]
Ich habe die Reifecam installiert und sie funktioniert soweit ganz gut.
Gibt es eine Einstellmöglichkeit in der mal definieren kann, dass automatisch alle x Stunen/ Minuten ein Bild abgespeichert wird?
Das fänd ich noch cool im Bezug auf das Zeitraffervideo

**Comment by Tronje-the-Falconer** [comment]
Die Webcam ist integriert es gibt aber keine automatische Aufnahme und Parameter zur Einstellung dafür

**Comment by sickboy2711** [comment]
Da ich die Webcam an der obersten Schiene verbaut habe steht mein Bild nun Kopf; macht vom Prinzip her nicht so extrem viel aus, ist halt nur ungewohnt.
Kannt du mir sagen, wo ich das Bild / den Stream drehen kann?
Normalerweise geht das ja beim pi mit `fswebcam --rotate 180 bild.jpg`
Finde aber in der Datei "webcam.php" nichts dazu auch im "sudowebscript.php" finde ich keinen Hinweis

**Comment by Tronje-the-Falconer** [comment]
Sorry für die verspätete Antwort.
Es wird beim streamen der Webcam mjpg_streamer verwendet. Im sudowebscript wird mit startwebcam  das Shellscript /opt/mjpg-streamer/webcam.sh ausgeführt. Dort kannst Du änderungen vornehmen um die Webcam zu drehen.
-rot 180 müsste der Parameter sein:

/opt/mjpg-streamer/mjpg_streamer -i "/opt/mjpg-streamer/input_uvc.so -d /dev/video0 -y -n -f 2" -rot 180 -o "/opt/mjpg-streamer/output_http.so -n -w /opt/mjpg-streamer/www" &

Wir können dies evtl. mal als Erweiterung versuchen einzubauen

**Comment by sickboy2711** [comment]
Hallo
Ich habe nun mal die Zeile von dir in das script eingesetzt und die andere auskommentiert.
Leider startet der Stream mit dem Zusatz danach gar nicht. 
Verwende die RC 3.2.1 von euch

**Comment by sickboy2711** [comment]
Wie ich jetzt gelesen habe wird die rot Funktion nur mittels Plugin input_raspicam unterstützt
[https://github.com/jacksonliam/mjpg-streamer/tree/master/mjpg-streamer-experimental/plugins/input_raspicam](url)
Der Pi-Ager hat jedoch nur das input_uvc installiert leider finde ich auf der Seite vom mjpg-streamer keine Anleitung wie ich die Plugins nachträglich installiere :-/

**Comment by GSV-DerBurgermeister** [comment]
Wurde in der letzten Version umgesetzt.
