### ISSUE TITLE
Portierung auf Python 3 (Besserer Treiber für SHT75 mir Reset-Funktion bei Kommunikationsproblemen)

### ISSUE THREAD

**Issue by ullibak** [Tronje-the-Falconer/Pi-Ager#31]
Bei mir ist der SHT75 sehr selten, aber im längeren Betreib dennoch schon mehrfach, "steckengeblieben" und ich musste den Raspberry Pi rebooten. Ich danke den Autoren dieser Steuerungsprogramm für ihre grosse Arbeit und möchte anregen, dass in einer kommenden Version ein Treiber für den SHT75 verwendet wird, der auch die Reset-Funktion nutzt. 

Ich bin fündig geworden, allerdings bedingt der Treiber, dass die gesamte Reifeschranksteuerung auf Python3 portiert werden muss. Was ich bisher gefunden (und gestetst) habe ist:

Treiber für SHT75 Temperatursensor: sudo pip3 install pi-sht1x 
(siehe https://github.com/drohm/pi-sht1x/)

**Für RRD-tool ist ebenfalls ein Update fällig:**

RRD-Tool Bindings installieren für Python 3: (von einem beliebigen Verzeichnis aus),
(siehe https://github.com/commx/python-rrdtool)
sudo apt-get install librrd-dev libpython3-dev
git clone https://github.com/commx/python-rrdtool.git
cd python-rrdtool
sudo python3.4 setup.py install

**Comment by GSV-Ha-Ma** [comment]
Das Problem trat bei mir auch auf als der Schirm vom Sensorkabel nicht auf Masse gelegt war .
Seit ich das gemacht habe hatte ich kein einziges Problem mehr. ( und ich verwende "nur" ein USB 2.0 Kabel)
Ein Versuch mit einem guten Kabel z. B. Cat6 und mit dem Schirm auf Masse lohnt sich ...
Bist du irgend wie im GSV Forum zu erreichen ?

**Comment by ullibak** [comment]
Vielen Dank für den Tipp. Werde meine Verkabelung verbessern. Generell aber kann es immer wieder passieren, dass durch Spannungs-Spikes oder andere Einflüsse die Kommunikation abbricht, da ist eine Reset-Funktion immer nützlich.
Bin bei GSV bisher nur "Leser".

Am 01.03.2017 um 09:38 schrieb GSV-Ha-Ma <notifications@github.com<mailto:notifications@github.com>>:


Das Problem trat bei mir auch auf als der Schirm vom Sensorkabel nicht auf Masse gelegt war .
Seit ich das gemacht habe hatte ich kein einziges Problem mehr. ( und ich verwende "nur" ein USB 2.0 Kabel)
Ein Versuch mit einem guten Kabel z. B. Cat6 und mit dem Schirm auf Masse lohnt sich ...
Bist du irgend wie im GSV Forum zu erreichen ?

**Comment by Tronje-the-Falconer** [comment]
In nächster Version enthalten
