### ISSUE TITLE
Luftzirkulation Geschwindigkeit regelbar machen 

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#39]
Es gibt Reifetabellen in denen die Luftgeschwindigkeit geregelt werden soll. Dies ist zu überlegen und dann  ggf. zu implementieren

**Comment by GSV-Ha-Ma** [comment]
Mit der 12V Ablufteinheit kann man die Lüftergeschwindigkeit manuell einstellen.
