### ISSUE TITLE
Instanzen der Scales starten und stoppen 

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#43]
Um den start/stop der scales.py zu vermeiden, sollten jeweils die Instanzen der Scales gestartet und gestoppt werden, damit die neuen Parameter aus der sqlite zum tragen kommen.

( samples, spikes, sleep, dout_data, pd_sck, gain, bitsToRead)

**Comment by GSV-Ha-Ma** [comment]
Parameter werden nach Anpassung direkt übernommen.
