### ISSUE TITLE
Weitere Komponenten mit Türkontaktschalter schalten/abschalten

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#45]
Wie bei dem UV-Licht könnte man andere komponenten mit einem Türkontaktschalter an bzw. ausschalten.

**Comment by GSV-Ha-Ma** [comment]
Denke bei Tür auf , UV aus und normales Licht an, das ist schonmal sinnvoll denke ich.

**Comment by phylax2020** [comment]
Fixed in rev 3.3.3 : Light and UV-Light can be controlled with Input port an the Pi-Ager board
