### ISSUE TITLE
Messenger benachrichtigung

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#51]
bei bestimmten Ereignissen eine nachricht an einen Messenger(z.B. Telegram) senden

**Comment by GSV-DerBurgermeister** [comment]
Main class for messenger created. First alarm and E-mail messeges.

**Comment by GSV-DerBurgermeister** [comment]
Not all done.

**Comment by GSV-DerBurgermeister** [comment]
With this method a mail can sended.
cl_fact_logic_messenger().get_instance().send('Hallo', 'Message_test')
Settings in the tables email_server and email_recipient are necessary.

**Comment by GSV-DerBurgermeister** [comment]
Messenger Klasse wurde erstellt. Es fehlt noch Telegramm und Pushover.

**Comment by GSV-DerBurgermeister** [comment]
Done
