### ISSUE TITLE
individuelles Diagramm

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#55]
Auf der Diagramm-Seite Sollte es ein diagramm geben, das durch Werte aus der Konfiguration erstellt wird, oder direkt auf der Diagrammseite

**Comment by GSV-Ha-Ma** [comment]
es sollen folgende Werte einstellbar sein: 

Messwerte:
- Temperatur min; Temperatur max
- Feuchtigkeit min ; Feuchtigkeit max

Zeitraum:
- Diagramm Anfangszeit und Endzeit, wobei diese Zeitspanne für alle Diagramme gelten soll

**Comment by GSV-Ha-Ma** [comment]
Die Waagenmesswerte müssen ja noch dazu...

Messwerte:

-  Waage1 min; Waage1 max
-  Waage2 min ; Waage2 max

**Comment by Tronje-the-Falconer** [comment]
implementiert
