### ISSUE TITLE
SHT75 Nachfolger codetechnisch unterstützen und testen

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#56]
https://www.sensirion.com/de/umweltsensoren/feuchtesensoren/steckbare-digitale-feuchtesensoren/

Der Feuchtesensor SHT7x erreicht das Ende seines Lebenszyklus und sollte nicht für neue Projekte verwendet werden.
Letztes Bestelldatum: 31.12.2018 / Letztes Lieferdatum: 31.12.2019
Ersatz: Ein Pin-kompatibles Ersatzprodukt basierend auf dem Feuchtesensor SHT3x wird ab Q3/2018 erhältlich sein.

**Comment by GSV-DerBurgermeister** [comment]
SHT3x und SHT85 werden im nächsten Release unterstützt.
