### ISSUE TITLE
Verzögerter Start der Reifetabelle

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#58]
Es  soll möglich sein, die Reifetabelle zu einem bestimmten Zeitpunkt zu starten.
Dafür ist ein Eingabefeld für den Startzeitpunkt auf der Webseite notwendig.
Beim schreiben in die Datenbanmk sollte der Zeitstempel geschrieben werden. mit diesem kann dann der Startzeitpunkt errechnet werden.
Der pi-ager-loop überprüft die Zeit. Sofern der Zeitpunkt erreicht ist, wird der status der agingtable auf 1 gesetzt

**Comment by GSV-Ha-Ma** [comment]
Mein Vorschlag zielte nicht auf solch einen verzögerten Start hinaus, ich meinte das Starten zu in einer bestimmten Phase wie in Punkt "Auswahl der Phase der Reifetabelle  #59" schon beschrieben.

**Comment by Tronje-the-Falconer** [comment]
wird nicht umgesetzt
