### ISSUE TITLE
Auswahl der Phase der Reifetabelle

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#59]
Es sollte auswählbar sein, zu welcher Periode die Reifetabelle startet.
Dafür muss vor jede Zeile ein Radiobutton eingebaut werden. Default selected ist Zeile 1

Beim speichern wird die gewählte Periode in die DB geschrieben.
Dieses Feld (bereits vorhanden) muss beim starten der agingtable ausgewertet werden.

**Comment by Tronje-the-Falconer** [comment]
Evtl. könnte noch ein feld für den tag innerhalb der periode sinnvoll sein.
Periode hat 3 tage und es soll ab da 2 der periode weitergemacht werden

**Comment by sickboy2711** [comment]
Hallo zusammen
Jetzt wo die Tage wieder kürzer werden verwende ich meinen Pi-Ager als Reifeschrenk für meine Rohwürste.
Der Vorschlag zum Auswählen der Phase der Reifetabelle finde ich super.
Klar kann man siech die Reifetabellen entsprechend kopieren und anpassen, jedoch wird die Auswahl dann recht gross und unüberschaubar.
Ist hier schon etwas in der Entwicklung?

**Comment by Tronje-the-Falconer** [comment]
implementiert
