### ISSUE TITLE
Monitor: Aktuelle Phase (Tag) und Start - Datum und Zeit darstellen

### ISSUE THREAD

**Issue by GSV-Ha-Ma** [Tronje-the-Falconer/Pi-Ager#60]
Auf der Monitor Seite sollte man die aktuell laufende Periode bzw Tag (wenn möglich) darstellen , zusätzlich macht es auch Sinn den Startzeitpunkt (Datum und Uhrzeit) auch anzuzeigen.

**Comment by Tronje-the-Falconer** [comment]
implementiert Startzeit wird nicht umgesetzt
