### ISSUE TITLE
Stunden/Minutenzähler für UV-Lampe

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Pi-Ager#63]
Eine UV-Lampe verringert auf Ihre Lebensdauer die intensität/Wirkung.
Daher muss die UV-Lampe nach bestimmter Dauer getauscht werden. Um die Brenndauer festzuhalten, sollte dies in der DB gelogt und auf der Webseite einsehbar sein.

folgende Tabellen:

Art | µW/m²
Bakterien | 10400
Viren | 6800

Species | Dose (mJ/cm2)
-- | --
Bacillus subtilis (spore) | 12.0
Clostridium tetani | 4.9
Legionella Pneumophilla | 2.04
Pseudonomas aeruginosa | 5.5
Streptococcus feacalis | 4.5
Hepatitis A | 11.0
Hepatitis Poliovirus | 12.0
Saccharomyces cervisiae | 6.0
Infektiöse pancreatic necrosis | 60.0

**Comment by GSV-Ha-Ma** [comment]
In Release 4.0.0 umgesetzt
