### ISSUE TITLE
USV

### ISSUE THREAD

**Issue by Flatmike** [Tronje-the-Falconer/Pi-Ager#65]
- Powerbank als USV
- mit Trafo (3V) an GPIO Versorgungsspannung überprüfen (da oder nicht?)
- Alternativ über (neue) Platine Powerbank laden und bei fehlender Versorgung als Stromquelle nutzen. Darüber dann Rückschluss auf vorhandenes Stromnetz.
- bei USV-Versorgung Prüfung, ob Netzwerk noch vorhanden 
- je nach Situation passende Aktionen ausführen (z.B. Piezo- Alarm, Mail verschicken, Webseiten-Benachrichtigung, blinkendes Display, Relais lösen)

**Comment by GSV-Ha-Ma** [comment]
Die Platine ist designed für ein USV Modul :
Adafruit PowerBoost 1000 
Link: https://www.adafruit.com/product/2465

Da das Modul max 1A liefern kann, darf es nur im Zusammenhang mit einem Raspberry Pi Zero W genutzt werde. Die anderen Modelle könnten das Modul überlasten.

Weitere Info zum Eisatz, siehe Herstellerseite.
