### ISSUE TITLE
Backup der SD-Karte

### ISSUE THREAD

**Issue by sickboy2711** [Tronje-the-Falconer/Pi-Ager#70]
Ich fände es besser, wenn mann ein Backup erstellen könnte ohne die ganze SD-Karte als Image zu sichern, so kann man schnell und einfach auch mal euf eine kleine Karte zurückgreien.

### Die Aktuelle Situation
Die Meisten von uns sichern ihr System indem sie die PI-Ager (hoffentlich sauber) herunterfahren, und die SD-Karte mit einem Program wie den Win32DiskImager am PC kopieren. 
Nachteil hieran ist jedoch, dass man immer midestens eine genauso grosse Karte benötiget vie man vorher eingesetzt hat.
Da gerade in der Test- und Probierphase oft gesichert und neugeschrieben wird stand ich genau vor diesem Problem und meine Kapazit an SD-Karten war schnell erschöpft

### Mein Lösungsvorschlag
Nun gibt es auf ein kleies aber feines Projekt Namens [PiShrink](https://github.com/Drewsif/PiShrink) welches genau dieses Problem behebt. Es löscht vom Backup alle ungeschriebenen Teile raus und schreibt ein Backup in der tatsächlichen Grösse.

Das Ganze habe ich nun in einem Script hinterlegt, welches es ermöglicht, über den PI ein Backup auf einem NFS-Mount zu erstellen, welches dann geshrinkt wird und dann wie gehabt mit einem Imagewriter-Toll auf die neue SD-Karte geschrieben werden kann.

Vieleicht hat ja wer Interesse sich das Script mal anzuschauen und zu testen

[backup.zip](https://github.com/Tronje-the-Falconer/Pi-Ager/files/2922857/backup.zip)

**Comment by GSV-DerBurgermeister** [comment]
Ist im nächsten Release eingebaut. Nur noch nicht über die Web-Oberfläche. Einstellungen müssen in Tabelle gemacht werden.
