### ISSUE TITLE
 dehumidify modus: only dehumidifier

### ISSUE THREAD

**Issue by Skiperich** [Tronje-the-Falconer/Pi-Ager#71]
### actual behavior

Pi-Ager 3.2.1.RC1
![mode_only_dehumidifier](https://user-images.githubusercontent.com/55779745/65676792-cba36780-e050-11e9-97d5-9b29597286a8.jpg)
[pi-ager_logfiles.zip](https://github.com/Tronje-the-Falconer/Pi-Ager/files/3657075/pi-ager_logfiles.zip)

In dehumidification mode: "only dehumidifier" if the exhaust fan is switched on by timer, it turns off only if the dehumidifier is on. Otherwise, the exhaust fan cannot be turned off.

**Comment by GSV-Ha-Ma** [comment]
Problem behoben in 4.0.0
