### ISSUE TITLE
Deprecated wiringpi mit pigpio ersetzen

### ISSUE THREAD

**Issue by wenners** [Tronje-the-Falconer/Pi-Ager#72]
### Expected behavior

Steuerung der GPIO Pins via Python (und nicht sudo)

### actual behavior

Steuerung der GPIO Pins via sudo und wiringpi.
Als ich per Hand mein Raspberry aufgesetzt habe, bin ich in mehrere Probleme gelaufen:

- sudo per php aus der Weboberfläche aufrufen ist nicht sooooo ganz best practice, hab' ich aber mal für den Moment wegignoriert
- Das Git, von dem wiringpi gecloned werden soll, ist aktuell nicht erreichbatr
- Raspberrian bringt ein wiringpi mit, allerdings hat das bei mir nicht sauber funktioniert
- Lt. Website ist wiringpi mittlerweile deprecated: http://wiringpi.com/wiringpi-deprecated/

### Possible Solution

Benutzung von pigpio http://abyz.me.uk/rpi/pigpio/
- pigpio bringt auch ein cli mit (pigs r 23 / pigs w 23 1)
- noch viel wichtiger: pigpio bringt python bindings mit so dass man auf Sicht schon mal Teile des sudoscripts obsolete machen könnte

Den ersten Teil setze ich schon erfolgreich ein, den zweiten werde ich mal ausprobieren. Wenn gewünscht, mach ich dafür dann gerne nen PR fertig...

**Comment by GSV-DerBurgermeister** [comment]
Das haben wir auf dem Schirm. Wir stellen momentan alles sukzessive auf Klassen um. Das sieht man im Branch "entwicklung". Da wird es dann eine GPIO Klasse geben, die pigpio ansteuert.

**Comment by GSV-DerBurgermeister** [comment]
Melde dich bitte mal per PN im GSV-Forum.

**Comment by phylax2020** [comment]
In the backend (python3) we use  exclusively RPi.GPIO to control the GPIO pins. We removed all GPIO control from sudowebscript.sh in version 3.3.0. Only in the frontend (php) we are using wiringpi with shell_exec(...) to read the GPIO pin status. As long as wiringpi is part of PI OS we do not need to use pigpio, particularly we can not make use of it directly from php.
