### ISSUE TITLE
SHT75

### ISSUE THREAD

**Issue by TheRealWolle** [Tronje-the-Falconer/Pi-Ager#73]
Hallo Tronje,

ich habe gerade meinen Rasberry Pi 3 B+ mit dem Pi-Ager_3.2.1.RC2.img in Betrieb genommen und getestet. Aber der Sensor SHT75 scheint nicht zu funktionieren. Wenn ich in den Settings den von mir verwendeten Sensor SHT75 anwähle und das abspeichere, springt die Auswahl auf einen anderen Sensor zurück. Im LOG steht dann:
**************************************************
19-11-15 15:04:32 wrong sensortype in settings
19-11-15 15:04:32 wrong sensortype in settings
19-11-15 15:05:02 wrong sensortype in settings

Kann es sein, dass der defekt ist, oder kann ich an den Einstellungen noch etwas ändern?

Vielen Dank im Voraus für die Hilfe

Ich bin echt begeistert von Eurer Arbeit

Herzliche Grüße
Wolle

**Comment by GSV-Ha-Ma** [comment]
Melde dich bitte im Forum oder unter : support@pi-ager.org so ist es einfacher direkt zu kommunizieren.
