### ISSUE TITLE
SHT75 Messfehler

### ISSUE THREAD

**Issue by chzinki** [Tronje-the-Falconer/Pi-Ager#77]
### Expected behavior

Normale Funktion des Pi-agers

### actual behavior

21-01-01 10:18:26 Exception raised: cx_measurement_error - To much measurment errors occured!Exception cx_measurement_error on Pi-Ager Hostname rpi-Pi-Ager occuredTraceback (most recent call last):
File "/opt/pi-ager/sensors/pi_ager_cl_sensor_sht75.py", line 56, in get_current_data
self._current_temperature = self._get_current_temperature()
File "/opt/pi-ager/sensors/pi_ager_cl_sensor_sht75.py", line 91, in _get_current_temperature
self._sensor_sht.read_temperature()
File "/usr/local/lib/python3.7/dist-packages/pi_sht1x/sht1x.py", line 166, in read_temperature
self._send_command()
File "/usr/local/lib/python3.7/dist-packages/pi_sht1x/sht1x.py", line 254, in _send_command
self._get_ack(command_name)
File "/usr/local/lib/python3.7/dist-packages/pi_sht1x/sht1x.py", line 397, in _get_ack
raise SHT1xError(message)
pi_sht1x.sht1x.SHT1xError: SHT1x failed to properly receive command [['Temperature'] - 00000011]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/pi-ager/pi_ager_loop.py", line 84, in get_sensordata
measured_data = main_sensor.get_current_data()
File "/opt/pi-ager/sensors/pi_ager_cl_sensor_sht75.py", line 61, in get_current_data
self.check_error_counter()
File "/opt/pi-ager/sensors/pi_ager_cl_sensor.py", line 61, in check_error_counter
raise cx_measurement_error ('To much measurment errors occured!')
main.pi_ager_cx_exception.cx_measurement_error: To much measurment errors occured!

21-01-01 10:18:26 Exception raised: KeyError - 'sensor_temperature'Exception KeyError on Pi-Ager Hostname rpi-Pi-Ager occuredTraceback (most recent call last):
File "/opt/pi-ager/pi_ager_loop.py", line 387, in doMainLoop
sensor_temperature = sensordata['sensor_temperature']
KeyError: 'sensor_temperature'

### Steps to reproduce the problem.

Der Schrank lief nun ca. 20 Wochen am Stück, z.T. in nur Kühlen Modus und im Automatik Modus. Der Fehler tritt seit 2 Tagen auf, nachdem meine Frau den Schrank mal für einen halben Tag offen stehen gelassen hat. Ich weiß nicht ob das damit was zu tun hat. Ein Neustart hat nichts gebracht. Habe mal versucht die Datenbank und die Logs zu löschen, was aber bei Überlegung auch keinen Einfluss haben sollte. Danach hat er aber z.T. auch sporadisch wieder für eine halbe Stunde funktioniert. 

### Possible Solution

Ein Hardwarefehler meinerseits ist auch nicht auszuschließen. Daher werde ich das Image die nächsten Tage frisch draufspielen.

### Specifications like the version of the project, operating system, or hardware
Drauf ist das Image 3.2.2 vom 26.09.2020. Der Sensor ist der SHT75 und aktueller Betriebsmodus ist Nur Kühlen.

**Comment by chzinki** [comment]
Ach ja und als Defaultwert ging der Schrank anscheinend auch mal in Kompressor dauerhaft an. Hab deshalb gerade -1°C im Schrank festgestellt. Vielleicht kann man auch prüfen ob es einen Safe State bei Sensorausfall gibt.

**Comment by GSV-DerBurgermeister** [comment]
Du kannst in der Tabelle config_messenger den Fehler cx_measurement_error mit raise_exception = 0 eintragen. Dann wird nicht abgebrochen und der Pi-Ager läuft weiter. Der eigentliche Fehler ist damit natürlich behoben. Es kann sein dass der SHT75 nicht mehr sauber misst. Sensoren altern auch.
![image](https://user-images.githubusercontent.com/43574434/103440793-f2375180-4c48-11eb-8fe3-41ed3f544145.png)

**Comment by chzinki** [comment]
Vielen Dank für die Hilfestellung, dann werde ich mir den Sensor mal vornehmen. Und übergangsweise die Exceptions ausstellen. Und echt ein riesen Lob an eure Arbeit!
