### ISSUE TITLE
Konfiguration E-Mail Versand

### ISSUE THREAD

**Issue by KnutKnusper** [Tronje-the-Falconer/Pi-Ager#82]
Laut Log File wird beim Einschalten des Raspberry Pis eine Email versendet. Leider finde ich hierzu keine Möglichkeit den Mailserver einzustellen und wann ich welche Daten versende.

Wo finde ich die Einstellungen?
Falls Möglich sollte dies mit in den Webserver oder die Setup.txt sowie in die Anleitung integrieren werden.

**Comment by GSV-DerBurgermeister** [comment]
Die Einstellung müssen im Release 3.2.2 und im Bugfix noch über phpliteadmin eingetragen werden wie hier beschrieben.
https://github.com/Tronje-the-Falconer/Pi-Ager/releases/download/3.2.2/2020-02-13_Messenger._E-Mail._Alarm._Pushover_und_Telegram.docx
Im nächsten Release, was in Arbeit ist, geht es über das Frontend.
