### ISSUE TITLE
Sprache im Webserver unter Einstellungen einheitlich machen

### ISSUE THREAD

**Issue by KnutKnusper** [Tronje-the-Falconer/Pi-Ager#83]
Im Webserver unter Einstellungen -> Manuelle Werte -> Texte (welche über die Hilfe Buttons eingeblendet werden) sollte in der eingestellten Sprache angezeigt werden. Aktuell wird Deutsch und Englisch gemischt angezeigt. 

Auch die Formatierung des eingeblendeten Textes müsste richtig gestellt werden. Hier sind unter Firefox, Chrome und Edge teilweise große Lücken im Text.

**Comment by GSV-DerBurgermeister** [comment]
Ist im neuen Release bereits übersetzt. Bevor wir das neue Release herausgeben werden wir nochmal alle prüfen.
