### ISSUE TITLE
FRQ: Umluft Lüfter mit UVC Bleuchtung zusammen schalten

### ISSUE THREAD

**Issue by KnutKnusper** [Tronje-the-Falconer/Pi-Ager#90]
**Problembeschreibung**
Um die UVC Beleuchtung nicht direkt auf das Fleisch strahlen zu lassen habe ich mir eine Box gebaut in welcher die UVC Beleuchtung integriert ist und durch welche der Umluft Lüfter die Kühlschrankluft bläst.
Damit eine indirekte Desinfektion über die UVC Leuchte möglich ist, müsste es eine Möglichkeit geben den Lüfter für die Umluft mit anzusteuern wenn die UVC Leuchte geschaltet wird.

**Versuchte Problembehebung**
Ich habe probiert die Zeiten von Zyklus und Dauer der UVC Leuchte und des Umluft Lüfters so einzustellen, dass diese gemeinsam eingeschaltet sind. Dies funktioniert aber leider nicht so wirklich. 

**Mögliche Umsetzung**
Checkbox in die Einstellungen einfügen über welchen man auswählen kann das der Umluft Lüfter gestartet werden soll wenn die UVC Leuchte an ist.

**Comment by GSV-Ha-Ma** [comment]
Für den Fall ist es sinnvoller einfach einen Lüfter parallel zur UV-Lampe anzuklemmnen und das so als Einheit zu betreiben.
Den "normalen" Umluftlüfter würde ich so lassen.

**Comment by samyness** [comment]
Hatte hier folgenden Lösungsansatz:

![IMG-20210404-WA0005](https://user-images.githubusercontent.com/63192089/122892877-16493500-d346-11eb-8e29-d2fd25a4c565.jpg)

**Comment by samyness** [comment]
Wurzel auf Lüfter, NO auf die Spannung, und NC auf den Ausgang von S1..
Dann schaltet die Lüftung automatisch wenn die Lampe leuchtet, und wenn der Lüfter geschalten ist, schaltet aber die Lampe nicht. :-)

**Comment by KnutKnusper** [comment]
Super Workaround! Da bin ich wohl gedanklich zu sehr bei der Software gewesen um das zu erkennen!
