### ISSUE TITLE
FRQ:  Funktion zur Verhinderung von Eisbildung am Wärmetauscher

### ISSUE THREAD

**Issue by GSV-Ha-Ma** [Tronje-the-Falconer/Pi-Ager#96]
Bei niedrigen Temperatursollwerten ( z.B. Dry Aging ) kommt es oft vor, dass sich am Wärmetauscher eine Eisschicht bildet, die dann eine isolierende Wirkung auf das System hat. Je dicker die Schicht ist, um so länger läuft der Kompressor, das führt dann zu einen höheren Stromverbrauch und zu einer schlechtere Regelung das Systems. (Temperatur und Feuchtigkeit)

In einem "normalen" Kühlschrank wird diese Eisbildung durch ein regelmäßiges gezieltes Abtauen das Systems verhindert.

Im Anhang ist der Prozess aus einen "normalen" Kühlschrank zu sehen. In regelmäßigen Zeitintervallen wird der Sollwert auf z.B. 4,5 Grad gestellt, während dieser Zeit taut das Eis auf und wird abgeführt.
Das Zeitintervall, in dem das Abtauen dann erfolgen soll, muss noch ermittelt/bestimmt werden (Vorschlag 1x in 24h). Der Sollwert 4,5 Grad muss auch nocht bestätigt werden.

![nofrost](https://user-images.githubusercontent.com/25824639/111297159-9b3cf800-864d-11eb-85a2-f2c80710b53b.jpeg)

**Comment by phylax2020** [comment]
Fixed in version 3.3.3
